name: Deploy to Lightsail

on:
  push:
    branches:
      - main  # Change to 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Lightsail via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/wuj-public-site
          git pull origin main
          sudo systemctl reload nginx
